In [1]:
import sys
from kaitoupao import *

storage dir: /Users/minkexiu/Downloads/GitHub/Tianchi_NLPNewsClassification
code dir: /Users/minkexiu/Documents/GitHub/Tianchi_NLPNewsClassification 

20 23 15
先天八卦数: 1乾, 2兑, 3离, 4震, 5巽, 6坎, 7艮, 8坤
本卦上：4 本卦下：7 变爻：3


雷山小过 泽风大过  雷地豫
上卦  ☳震木  ☱兑金  ☳震木
下卦  ☶艮土  ☴巽木  ☷坤土

12 21 1 子时
先天八卦数: 1乾, 2兑, 3离, 4震, 5巽, 6坎, 7艮, 8坤
本卦上：4 本卦下：5 变爻：1


雷风恒  泽天夬 雷天大壮
上卦  ☳震木  ☱兑金  ☳震木
下卦  ☴巽木  ☰乾金  ☰乾金

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset, Dataset
from torch.nn.utils.rnn import pad_sequence
from sklearn.metrics import f1_score

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
device = torch.device("mps")

In [81]:
torch.tensor([1,2,3,4,5], dtype=torch.float32).unsqueeze(0)

tensor([[1., 2., 3., 4., 5.]])

In [59]:
t1 = torch.tensor([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]], dtype=torch.float32)

In [60]:
t1

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])

In [61]:
l1 = nn.Linear(3, 1)

In [69]:
l1(t1.permute(1,0)).permute(1,0).squeeze()

tensor([-1.6502, -1.5901, -1.5300, -1.4700, -1.4099],
       grad_fn=<SqueezeBackward0>)

In [67]:
for prm in l1.parameters():
    print(prm)

Parameter containing:
tensor([[ 0.4533, -0.4253,  0.0321]], requires_grad=True)
Parameter containing:
tensor([0.0955], requires_grad=True)


In [78]:
torch.cat([
    l1(t1.permute(1,0)).permute(1,0),
    l1(t1.permute(1,0)).permute(1,0),
    l1(t1.permute(1,0)).permute(1,0),
    l1(t1.permute(1,0)).permute(1,0)
],dim=0)

tensor([[-1.6502, -1.5901, -1.5300, -1.4700, -1.4099],
        [-1.6502, -1.5901, -1.5300, -1.4700, -1.4099],
        [-1.6502, -1.5901, -1.5300, -1.4700, -1.4099],
        [-1.6502, -1.5901, -1.5300, -1.4700, -1.4099]], grad_fn=<CatBackward0>)

In [5]:
import torch.nn as nn
from transformers import AdamW
from torch.utils.data import Dataset
import pandas as pd
import torch
from transformers import BertConfig, BertForSequenceClassification
from transformers import BertTokenizer
from torch.utils.data import DataLoader

In [37]:
tokenizer = BertTokenizer(vocab_file="./untitled.txt")

In [38]:
tokenizer.tokenize("this")

['[UNK]']

In [48]:
from transformers import BertConfig
from transformers import BertForSequenceClassification

config = BertConfig(
vocab_size=100,
hidden_size=512,
num_hidden_layers=6,
num_attention_heads=8,
intermediate_size=2048,
max_position_embeddings=512,
num_labels=5
)

model = BertForSequenceClassification(config)

In [49]:
model.forward?

Signature:
model.forward(
    input_ids: Optional[torch.Tensor] = None,
    attention_mask: Optional[torch.Tensor] = None,
    token_type_ids: Optional[torch.Tensor] = None,
    position_ids: Optional[torch.Tensor] = None,
    head_mask: Optional[torch.Tensor] = None,
    inputs_embeds: Optional[torch.Tensor] = None,
    labels: Optional[torch.Tensor] = None,
    output_attentions: Optional[bool] = None,
    output_hidden_states: Optional[bool] = None,
    return_dict: Optional[bool] = None,
) -> Union[Tuple[torch.Tensor], transformers.modeling_outputs.SequenceClassifierOutput]
Docstring:
The [`BertForSequenceClassification`] forward method, overrides the `__call__` special method.

<Tip>

Although the recipe for forward pass needs to be defined within this function, one should call the [`Module`]
instance afterwards instead of this since the former takes care of running the pre and post processing steps while
the latter silently ignores them.

</Tip>

Args:
    input_ids (`torch.LongT

In [50]:
outputs = model(input_ids=torch.tensor([[1,2,3,4,5]], dtype=torch.long))

In [51]:
outputs.logits

tensor([[ 0.1212, -0.0173, -0.4758,  0.0187,  0.3480]],
       grad_fn=<AddmmBackward0>)